version: 1
build:
  env: docker
  buildCommand: bash build.sh
  publishPath: public
services:
  - type: web
    name: sports-booking
    env: docker
    buildCommand: bash build.sh
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
